import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { Collapsible } from '@components/collapsible';

// export default {
//   title: 'Collapsible',
//   component: Collapsible,
// } as ComponentMeta<typeof Collapsible>;

// const Template: ComponentStory<typeof Collapsible> = (args) => <Collapsible {...args} />;

// export const Default = Template.bind({});
// Default.args = {
//   isiTitle: 'IMPORTANT SAFETY INFORMATION',
//   isiTopText: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed commodo fermentum augue, ut imperdiet purus sollicitudin et. Curabitur nec tristique enim. Pellentesque libero nunc, ornare eget malesuada at, dapibus sed dolor. Phasellus lacus dolor, convallis nec commodo eget, auctor eget leo. Integer quis augue imperdiet, eleifend odio sed, hendrerit sapien. Curabitur viverra feugiat lectus, non dapibus dolor rhoncus vitae. Pellentesque porttitor lorem non ex laoreet blandit. Maecenas semper arcu ut quam lobortis, sed lobortis elit porttitor. Proin consectetur lectus ligula, vel ornare nunc vehicula eu. Ut vulputate nibh vitae dui posuere eleifend. Suspendisse ac quam ac metus maximus pellentesque a id mi. Nulla eu nisl massa. Nam quis nibh at magna facilisis faucibus nec in ipsum. Integer libero metus, accumsan non posuere ut, placerat vitae eros. Suspendisse convallis, sapien ut viverra sodales, eros odio imperdiet ante, a dapibus enim erat ut felis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed commodo fermentum augue, ut imperdiet purus sollicitudin et. Curabitur nec tristique enim. Pellentesque libero nunc, ornare eget malesuada at, dapibus sed dolor. Phasellus lacus dolor, convallis nec commodo eget, auctor eget leo.',
//   indicationTitle: 'INDICATIONS',
//   indicationText: 'indication ,Lorem ipsum dolor sit amet orem ipsum dolor sit amet, consectetur adipiscing elit. Sed commodo fermentum augue, ut imperdiet purus sollicitudin et. Curabitur nec tristique enim. Lorem ipsum dolor sit amet orem ipsum dolor sit amet, consectetur adipiscing elit. Sed commodo fermentum augue, ut imperdiet purus sollicitudin et. Curabitur nec tristique enim.',
//   isiBottomText: 'Part two, Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed commodo fermentum augue, ut imperdiet purus sollicitudin et. Curabitur nec tristique enim. Pellentesque libero nunc, ornare eget malesuada at, dapibus sed dolor. Phasellus lacus dolor, convallis nec commodo eget, auctor eget leo. Integer quis augue imperdiet, eleifend odio sed, hendrerit sapien. Curabitur viverra feugiat lectus, non dapibus dolor rhoncus vitae. Pellentesque porttitor lorem non ex laoreet blandit. Maecenas semper arcu ut quam lobortis, sed lobortis elit porttitor. Proin consectetur lectus ligula, vel ornare nunc vehicula eu. Ut vulputate nibh vitae dui posuere eleifend. Suspendisse ac quam ac metus maximus pellentesque a id mi. Nulla eu nisl massa. Nam quis nibh at magna facilisis faucibus nec in ipsum. Integer libero metus, accumsan non posuere ut, placerat vitae eros. Suspendisse convallis, sapien ut viverra sodales, eros odio imperdiet ante, a dapibus enim erat ut felis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed commodo fermentum augue, ut imperdiet purus sollicitudin et. Curabitur nec tristique enim. Pellentesque libero nunc, ornare eget malesuada at, dapibus sed dolor. Phasellus lacus dolor, convallis nec commodo eget, auctor eget leo. Integer quis augue imperdiet, eleifend odio sed, hendrerit sapien. Curabitur viverra feugiat lectus, non dapibus dolor rhoncus vitae. Pellentesque porttitor lorem non ex laoreet blandit. Maecenas semper arcu ut quam lobortis, sed lobortis elit porttitor. Proin consectetur lectus ligula, vel ornare nunc vehicula eu. Ut vulputate nibh vitae dui posuere eleifend. Suspendisse ac quam ac metus maximus pellentesque a id mi. Nulla eu nisl massa. Nam quis nibh at magna facilisis faucibus nec in ipsum. Integer libero metus, accumsan non posuere ut, placerat vitae eros. Suspendisse convallis, sapien ut viverra sodales, eros odio imperdiet ante, a dapibus enim erat ut felis.',
// };
